/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AgkMenu {
        "autoIdentifier": string;
        "disabled": boolean;
        "errorText": string;
        "hasError": boolean;
        "label": string;
        "name": string;
        "options": string;
        "placeHolder": string;
        "setFocus": () => Promise<void>;
        "value": string;
    }
}
export interface AgkMenuCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLAgkMenuElement;
}
declare global {
    interface HTMLAgkMenuElement extends Components.AgkMenu, HTMLStencilElement {
    }
    var HTMLAgkMenuElement: {
        prototype: HTMLAgkMenuElement;
        new (): HTMLAgkMenuElement;
    };
    interface HTMLElementTagNameMap {
        "agk-menu": HTMLAgkMenuElement;
    }
}
declare namespace LocalJSX {
    interface AgkMenu {
        "autoIdentifier"?: string;
        "disabled"?: boolean;
        "errorText"?: string;
        "hasError"?: boolean;
        "label"?: string;
        "name"?: string;
        "onAgkMenuBlur"?: (event: AgkMenuCustomEvent<any>) => void;
        "onAgkMenuChange"?: (event: AgkMenuCustomEvent<any>) => void;
        "onAgkMenuFocus"?: (event: AgkMenuCustomEvent<any>) => void;
        "options"?: string;
        "placeHolder"?: string;
        "value"?: string;
    }
    interface IntrinsicElements {
        "agk-menu": AgkMenu;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "agk-menu": LocalJSX.AgkMenu & JSXBase.HTMLAttributes<HTMLAgkMenuElement>;
        }
    }
}
